packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  storybook: 10.2.10
  '@storybook/nextjs': 10.2.10
  '@storybook/react': 10.2.10
  '@storybook/addon-docs': 10.2.10
  '@storybook/addon-a11y': 10.2.10
  '@storybook/addon-vitest': 10.2.10
  'eslint-plugin-storybook': 10.2.10

onlyBuiltDependencies:
  - core-js-pure
  - esbuild
  - msw
  - sharp
  - unrs-resolver
