import type { TestCaseTemplate } from './types';

export const TEMPLATE_CATEGORY_OPTIONS = [
  { value: 'BUILTIN', label: '빌트인' },
  { value: 'CUSTOM', label: '커스텀' },
] as const;

export const BUILTIN_TEMPLATE_IDS = {
  BASIC: 'builtin-basic',
  STEP_BY_STEP: 'builtin-step-by-step',
  EXPLORATORY: 'builtin-exploratory',
  BDD: 'builtin-bdd',
  CHECKLIST: 'builtin-checklist',
} as const;

export const BUILTIN_TEMPLATES: TestCaseTemplate[] = [
  {
    id: BUILTIN_TEMPLATE_IDS.BASIC,
    projectId: '',
    name: '로그인 기능 테스트',
    description: '이메일/비밀번호 기반 로그인 기능의 정상 동작과 예외 케이스를 검증하는 기본 템플릿입니다.',
    category: 'BUILTIN',
    testType: 'functional',
    defaultTags: ['로그인', '인증', '기능테스트'],
    preCondition: '1. 테스트 계정이 생성되어 있어야 합니다. (test@example.com / Test1234!)\n2. 로그인 페이지에 접근 가능한 상태여야 합니다.\n3. 이전 세션이 로그아웃된 상태여야 합니다.',
    testSteps: '1. 로그인 페이지(/login)에 접속한다.\n2. 이메일 입력 필드에 "test@example.com"을 입력한다.\n3. 비밀번호 입력 필드에 "Test1234!"를 입력한다.\n4. "로그인" 버튼을 클릭한다.\n5. 대시보드 페이지로 리다이렉트되는지 확인한다.\n6. 헤더에 사용자 이름이 표시되는지 확인한다.',
    expectedResult: '1. 로그인 성공 후 대시보드(/dashboard)로 리다이렉트된다.\n2. 헤더에 사용자 이름 "테스트 유저"가 표시된다.\n3. 인증 토큰이 쿠키에 저장된다.\n4. 브라우저를 새로고침해도 로그인 상태가 유지된다.',
    usageCount: 0,
    sortOrder: 0,
    lifecycleStatus: 'ACTIVE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: BUILTIN_TEMPLATE_IDS.STEP_BY_STEP,
    projectId: '',
    name: '회원가입 프로세스 검증',
    description: '회원가입의 각 단계를 순서대로 검증하는 단계별 상세 템플릿입니다. 입력 유효성 검사, 중복 확인, 인증 메일까지 포함합니다.',
    category: 'BUILTIN',
    testType: 'functional',
    defaultTags: ['회원가입', '인증', '유효성검사', 'E2E'],
    preCondition: '1. 회원가입 페이지에 접근 가능한 상태여야 합니다.\n2. 테스트용 이메일 수신이 가능해야 합니다. (메일 서비스 또는 Mailhog 등)\n3. 기존에 동일 이메일로 가입된 계정이 없어야 합니다.',
    testSteps: '1. 회원가입 페이지(/signup)에 접속한다.\n2. 이름 필드에 "홍길동"을 입력한다.\n3. 이메일 필드에 "newuser@example.com"을 입력한다.\n4. 이메일 중복 확인 버튼을 클릭하고 "사용 가능" 메시지를 확인한다.\n5. 비밀번호 필드에 "SecurePass1!"을 입력한다.\n6. 비밀번호 강도 표시기가 "강함"으로 표시되는지 확인한다.\n7. 비밀번호 확인 필드에 "SecurePass1!"을 입력한다.\n8. 이용약관 체크박스를 선택한다.\n9. 개인정보 처리방침 체크박스를 선택한다.\n10. "가입하기" 버튼을 클릭한다.\n11. 이메일 인증 안내 페이지가 표시되는지 확인한다.\n12. 수신된 인증 메일의 링크를 클릭한다.\n13. 가입 완료 페이지가 표시되는지 확인한다.',
    expectedResult: '1. 이메일 중복 확인 시 "사용 가능한 이메일입니다" 메시지가 표시된다.\n2. 비밀번호 강도가 "강함"으로 표시된다.\n3. 가입하기 버튼 클릭 후 이메일 인증 안내 페이지로 이동한다.\n4. 인증 메일이 1분 이내에 수신된다.\n5. 인증 링크 클릭 후 가입 완료 페이지가 표시된다.\n6. 가입된 계정으로 로그인이 가능하다.',
    usageCount: 0,
    sortOrder: 1,
    lifecycleStatus: 'ACTIVE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: BUILTIN_TEMPLATE_IDS.EXPLORATORY,
    projectId: '',
    name: '결제 흐름 탐색적 테스트',
    description: '결제 프로세스 전반을 자유롭게 탐색하며 예상치 못한 버그나 UX 문제를 발견하는 탐색적 테스트 템플릿입니다.',
    category: 'BUILTIN',
    testType: 'functional',
    defaultTags: ['결제', '탐색적테스트', 'UX', '엣지케이스'],
    preCondition: '1. 테스트 결제 환경(Sandbox/Staging)이 설정되어 있어야 합니다.\n2. 테스트용 카드 정보가 준비되어 있어야 합니다. (성공/실패/잔액부족 각각)\n3. 장바구니에 1개 이상의 상품이 담겨 있어야 합니다.\n4. 로그인된 상태여야 합니다.',
    testSteps: '탐색 영역: 상품 선택 → 장바구니 → 주문서 → 결제 → 완료 전체 흐름\n\n탐색 목표:\n- 결제 수단 변경 시 금액 계산이 정확한지 확인\n- 네트워크 지연/끊김 상황에서의 동작 확인\n- 뒤로가기, 새로고침, 중복 클릭 등 비정상 흐름 테스트\n- 쿠폰/포인트 적용 및 취소 반복 시 금액 정합성 확인\n\n탐색 시나리오:\n1. 여러 상품을 장바구니에 담았다가 일부만 삭제 후 결제 시도\n2. 결제 진행 중 뒤로가기 후 다시 결제 시도\n3. 쿠폰 적용 → 취소 → 다른 쿠폰 적용 반복\n4. 결제 버튼 빠르게 연속 클릭\n5. 결제 중 네트워크 차단 후 복구\n6. 여러 탭에서 동시에 같은 주문 결제 시도\n\n시간 제한: 60분',
    expectedResult: '1. 모든 금액 계산이 정확해야 한다. (소수점, 할인, 배송비 포함)\n2. 중복 결제가 발생하지 않아야 한다.\n3. 비정상 흐름에서 적절한 에러 메시지가 표시되어야 한다.\n4. 결제 실패 시 재시도가 가능해야 한다.\n5. 발견된 모든 이슈를 심각도(Critical/Major/Minor)와 함께 기록한다.',
    usageCount: 0,
    sortOrder: 2,
    lifecycleStatus: 'ACTIVE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: BUILTIN_TEMPLATE_IDS.BDD,
    projectId: '',
    name: '장바구니 기능 (BDD)',
    description: 'Given-When-Then 형식으로 장바구니 추가/수정/삭제 시나리오를 작성하는 BDD 스타일 템플릿입니다.',
    category: 'BUILTIN',
    testType: 'functional',
    defaultTags: ['장바구니', 'BDD', 'E2E'],
    preCondition: 'Given: 사용자가 로그인된 상태이다.\nAnd: 상품 목록 페이지에 접근한 상태이다.\nAnd: "테스트 상품 A" (10,000원)가 판매 중이다.\nAnd: 장바구니가 비어있는 상태이다.',
    testSteps: 'Scenario 1: 상품을 장바구니에 추가한다\nWhen: 사용자가 "테스트 상품 A"의 "장바구니 담기" 버튼을 클릭한다.\nThen: 장바구니에 "테스트 상품 A"가 수량 1개로 추가된다.\nAnd: 헤더의 장바구니 아이콘에 숫자 "1"이 표시된다.\nAnd: "장바구니에 담겼습니다" 토스트 메시지가 표시된다.\n\nScenario 2: 장바구니에서 수량을 변경한다\nGiven: 장바구니에 "테스트 상품 A"가 1개 담겨있다.\nWhen: 수량 증가(+) 버튼을 2번 클릭한다.\nThen: 수량이 3개로 변경된다.\nAnd: 소계가 30,000원으로 업데이트된다.\n\nScenario 3: 장바구니에서 상품을 삭제한다\nGiven: 장바구니에 "테스트 상품 A"가 담겨있다.\nWhen: 해당 상품의 "삭제" 버튼을 클릭한다.\nAnd: 확인 다이얼로그에서 "삭제"를 선택한다.\nThen: 장바구니에서 해당 상품이 제거된다.\nAnd: "장바구니가 비어있습니다" 메시지가 표시된다.',
    expectedResult: 'Then: 모든 시나리오가 정상적으로 동작한다.\nAnd: 장바구니 수량과 금액 계산이 정확하다.\nAnd: 페이지 새로고침 후에도 장바구니 데이터가 유지된다.\nAnd: 재고 초과 수량 입력 시 적절한 안내 메시지가 표시된다.',
    usageCount: 0,
    sortOrder: 3,
    lifecycleStatus: 'ACTIVE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: BUILTIN_TEMPLATE_IDS.CHECKLIST,
    projectId: '',
    name: '배포 전 스모크 테스트',
    description: '프로덕션 배포 전 핵심 기능의 정상 동작을 빠르게 확인하는 스모크 테스트 체크리스트입니다.',
    category: 'BUILTIN',
    testType: 'smoke',
    defaultTags: ['스모크테스트', '배포', 'QA체크리스트'],
    preCondition: '1. 스테이징 환경에 최신 빌드가 배포된 상태여야 합니다.\n2. 테스트 계정 정보가 준비되어 있어야 합니다.\n3. 외부 연동 서비스(결제, 이메일 등)가 정상 동작하는 상태여야 합니다.',
    testSteps: '■ 인증\n- [ ] 회원가입 페이지가 정상 로드된다\n- [ ] 로그인이 정상적으로 동작한다\n- [ ] 로그아웃 후 보호된 페이지 접근 시 로그인 페이지로 리다이렉트된다\n\n■ 핵심 기능\n- [ ] 메인 페이지가 3초 이내에 로드된다\n- [ ] 상품 목록이 정상적으로 표시된다\n- [ ] 상품 상세 페이지가 정상적으로 표시된다\n- [ ] 검색 기능이 정상 동작한다\n- [ ] 장바구니 추가/삭제가 정상 동작한다\n\n■ 결제\n- [ ] 주문서 작성 페이지가 정상 로드된다\n- [ ] 테스트 결제가 정상 완료된다\n- [ ] 주문 완료 페이지가 표시된다\n- [ ] 주문 내역에서 결제 건이 조회된다\n\n■ 공통\n- [ ] 404 페이지가 정상 표시된다\n- [ ] 모바일 반응형 레이아웃이 깨지지 않는다\n- [ ] 콘솔에 Critical 에러가 없다\n- [ ] API 응답 시간이 2초 이내이다',
    expectedResult: '1. 모든 체크리스트 항목이 통과(Pass)되어야 한다.\n2. 실패 항목이 있을 경우 심각도를 표기하고 배포 여부를 판단한다.\n   - Critical 실패: 배포 중단\n   - Major 실패: 수정 후 재배포\n   - Minor 실패: 이슈 등록 후 배포 진행 가능',
    usageCount: 0,
    sortOrder: 4,
    lifecycleStatus: 'ACTIVE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export function isBuiltinTemplate(id: string): boolean {
  return Object.values(BUILTIN_TEMPLATE_IDS).includes(id as (typeof BUILTIN_TEMPLATE_IDS)[keyof typeof BUILTIN_TEMPLATE_IDS]);
}
