import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@/app-shell/styles/globals.css';
import { MvpBottomNavbar } from 'src/shared';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* 테스트용 컴포넌트 */}
        <MvpBottomNavbar/>
      </body>
    </html>
  );
}
