import type { TestCaseTemplate } from './types';

export const TEMPLATE_CATEGORY_OPTIONS = [
  { value: 'BUILTIN', label: '빌트인' },
  { value: 'CUSTOM', label: '커스텀' },
] as const;

export const BUILTIN_TEMPLATE_IDS = {
  BASIC: 'builtin-basic',
  STEP_BY_STEP: 'builtin-step-by-step',
  EXPLORATORY: 'builtin-exploratory',
  BDD: 'builtin-bdd',
  CHECKLIST: 'builtin-checklist',
} as const;

export const BUILTIN_TEMPLATES: TestCaseTemplate[] = [
  {
    id: BUILTIN_TEMPLATE_IDS.BASIC,
    projectId: '',
    name: 'Basic',
    description: '기본 테스트 케이스 템플릿. 제목, 사전 조건, 테스트 단계, 기대 결과를 포함합니다.',
    category: 'BUILTIN',
    testType: 'functional',
    defaultTags: [],
    preCondition: '',
    testSteps: '',
    expectedResult: '',
    usageCount: 0,
    sortOrder: 0,
    lifecycleStatus: 'ACTIVE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: BUILTIN_TEMPLATE_IDS.STEP_BY_STEP,
    projectId: '',
    name: 'Step-by-Step',
    description: '단계별 상세 테스트 케이스. 각 단계에 번호를 매겨 순서대로 진행합니다.',
    category: 'BUILTIN',
    testType: 'functional',
    defaultTags: [],
    preCondition: '1. 테스트 환경이 준비되어 있어야 합니다.\n2. 테스트 데이터가 세팅되어 있어야 합니다.',
    testSteps: '1. [첫 번째 동작을 입력하세요]\n2. [두 번째 동작을 입력하세요]\n3. [세 번째 동작을 입력하세요]',
    expectedResult: '1. [첫 번째 기대 결과]\n2. [두 번째 기대 결과]\n3. [세 번째 기대 결과]',
    usageCount: 0,
    sortOrder: 1,
    lifecycleStatus: 'ACTIVE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: BUILTIN_TEMPLATE_IDS.EXPLORATORY,
    projectId: '',
    name: 'Exploratory',
    description: '탐색적 테스트 템플릿. 자유롭게 탐색하며 버그를 발견하는 데 초점을 맞춥니다.',
    category: 'BUILTIN',
    testType: 'functional',
    defaultTags: ['exploratory'],
    preCondition: '테스트 대상 기능에 접근 가능한 상태',
    testSteps: '탐색 영역: [테스트할 기능/영역]\n탐색 목표: [발견하고자 하는 것]\n탐색 방법: [어떻게 테스트할 것인지]\n시간 제한: [탐색 시간]',
    expectedResult: '발견된 이슈를 기록하세요.',
    usageCount: 0,
    sortOrder: 2,
    lifecycleStatus: 'ACTIVE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: BUILTIN_TEMPLATE_IDS.BDD,
    projectId: '',
    name: 'BDD (Given-When-Then)',
    description: 'BDD 스타일 템플릿. Given-When-Then 형식으로 시나리오를 작성합니다.',
    category: 'BUILTIN',
    testType: 'functional',
    defaultTags: ['bdd'],
    preCondition: 'Given: [초기 상태/전제 조건]',
    testSteps: 'When: [사용자 행동/이벤트]',
    expectedResult: 'Then: [기대 결과/검증 항목]',
    usageCount: 0,
    sortOrder: 3,
    lifecycleStatus: 'ACTIVE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: BUILTIN_TEMPLATE_IDS.CHECKLIST,
    projectId: '',
    name: 'Checklist',
    description: '체크리스트 스타일 템플릿. 확인 항목을 나열하여 빠르게 검증합니다.',
    category: 'BUILTIN',
    testType: 'smoke',
    defaultTags: ['checklist'],
    preCondition: '',
    testSteps: '- [ ] 확인 항목 1\n- [ ] 확인 항목 2\n- [ ] 확인 항목 3\n- [ ] 확인 항목 4\n- [ ] 확인 항목 5',
    expectedResult: '모든 체크리스트 항목이 통과되어야 합니다.',
    usageCount: 0,
    sortOrder: 4,
    lifecycleStatus: 'ACTIVE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export function isBuiltinTemplate(id: string): boolean {
  return Object.values(BUILTIN_TEMPLATE_IDS).includes(id as (typeof BUILTIN_TEMPLATE_IDS)[keyof typeof BUILTIN_TEMPLATE_IDS]);
}
