import type { MilestoneWithStats } from './types';
import { MOCK_PROJECT_ID } from '@/shared';

export const milestonesMock: MilestoneWithStats[] = [
  {
    id: 'ms_v1_0',
    projectId: MOCK_PROJECT_ID,
    title: 'v1.0 릴리즈',
    progressStatus: 'inProgress',
    description: '정식 릴리즈 전 핵심 플로우 회귀 테스트와 주요 기능 검증',
    startDate: new Date('2024-12-15'),
    endDate: new Date('2024-12-25'),
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-10'),
    archivedAt: null,
    lifecycleStatus: 'ACTIVE',
    totalCases: 45,
    completedCases: 38,
    progressRate: 84,
    runCount: 3,
  },
  {
    id: 'ms_v1_1_beta',
    projectId: MOCK_PROJECT_ID,
    title: 'v1.1 베타',
    progressStatus: 'inProgress',
    description: '사용자 피드백 기반 개선 항목을 베타 환경에서 검증',
    startDate: new Date('2024-12-28'),
    endDate: new Date('2025-01-10'),
    createdAt: new Date('2024-12-20'),
    updatedAt: new Date('2024-12-20'),
    archivedAt: null,
    lifecycleStatus: 'ACTIVE',
    totalCases: 28,
    completedCases: 12,
    progressRate: 43,
    runCount: 1,
  },
  {
    id: 'ms_bug_sprint',
    projectId: MOCK_PROJECT_ID,
    title: '버그 수정 스프린트',
    progressStatus: 'done',
    description: '릴리즈 전 발견된 크리티컬 이슈를 집중적으로 해결한 스프린트',
    startDate: new Date('2024-12-01'),
    endDate: new Date('2024-12-10'),
    createdAt: new Date('2024-11-25'),
    updatedAt: new Date('2024-11-30'),
    archivedAt: null,
    lifecycleStatus: 'ACTIVE',
    totalCases: 15,
    completedCases: 15,
    progressRate: 100,
    runCount: 2,
  },
  {
    id: 'ms_next_plan',
    projectId: MOCK_PROJECT_ID,
    title: 'v1.2 계획',
    progressStatus: 'planned',
    description: '다음 분기 개선 항목 정리와 범위 확정',
    startDate: new Date('2025-01-15'),
    endDate: new Date('2025-01-31'),
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date('2025-01-05'),
    archivedAt: null,
    lifecycleStatus: 'ACTIVE',
    totalCases: 0,
    completedCases: 0,
    progressRate: 0,
    runCount: 0,
  },
];
